services:
  web:
    build:
      context: app
      target: builder
    ports:
      - '80:80'
    networks:
      - backend
  db:
    image: 'mysql:8.1.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '!ChangeMe!'
    networks:
      - backend

networks:
  backend: