services:
  db:
    image: 'mysql:8.1.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '!ChangeMe!'
    networks:
      - backend
  web:
    build:
      context: app
      target: builder
    ports:
      - '80:80'
    networks:
      - backend
    depends_on:
      - db

  migration:
    build:
      context: app
      target: builder
    command: /bin/sh -c "/db-migrate.sh"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend: